CREATE DATABASE SIS_VEN_WEB

CREATE TABLE EMPLEADO
(
	EMP_ID INT PRIMARY KEY,
	EMP_NOMBRE VARCHAR(20)NOT NULL,
	EMP_APELLIDOPAT VARCHAR(20) NULL,
	EMP_APELLIDOMAT VARCHAR(20)NOT NULL,
	EMP_CURP VARCHAR(20)NOT NULL,
	EMP_CELULAR VARCHAR(13)NOT NULL,
)

CREATE TABLE PAGO_TIPO 
(
	PAG_ID INT PRIMARY KEY IDENTITY(1,1),
	PAG_NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE CLIENTE
(
	CLI_ID  INT PRIMARY KEY,
	CLI_NOMBRE VARCHAR(15)NOT NULL,				 
	CLI_APELLIDOS VARCHAR(100) NULL,	 		 
	CLI_CELULAR VARCHAR(13)NOT NULL,			 			 				 
	CLI_DIRECCION VARCHAR(100)NOT NULL, 
	CLI_FECHANA DATE NOT NULL,
	CLI_TIPOPAGO INT FOREIGN KEY REFERENCES PAGO_TIPO(PAG_ID) NOT NULL
)

CREATE TABLE PROVEEDOR
(
	PROV_ID INT PRIMARY KEY,
	PROV_EMPRESA VARCHAR(20)NOT NULL,
	PROV_CORREO VARCHAR(30)NOT NULL,
	PROV_DIRECCION VARCHAR(40)NOT NULL,
	PROV_TELEFONO VARCHAR(13)NOT NULL
)

CREATE TABLE PRODUCTO
(
	PROD_ID INT PRIMARY KEY,
	PROD_CODIGO VARCHAR(10)NOT NULL,
	PROD_NOMBRE VARCHAR(20)NOT NULL,
	PROD_DESCRIPCION VARCHAR(30)NOT NULL,
	PROD_STOCK INT NOT NULL,
	PROD_PROV_ID INT FOREIGN KEY REFERENCES PROVEEDOR(PROV_ID),
	PROD_PRECIOCOMPRA DECIMAL NOT NULL,
	PROD_PRECIOVENTA DECIMAL NOT NULL,
	PROD_ESTADO BIT NOT NULL,
	--PROD_CAT_ID INT FOREIGN KEY REFERENCES CATEGORIA(CAT_ID)
)

CREATE TABLE DEPARTAMENTO
(
	DEP_ID INT PRIMARY KEY IDENTITY(1,1),
	DEP_NOMBRE VARCHAR(100) NOT NULL
)

CREATE TABLE PUESTO 
(
	PUE_ID INT PRIMARY KEY IDENTITY(1,1),
	PUE_NOMBRE VARCHAR(100) NOT NULL,
	PUE_DEP_ID INT FOREIGN KEY REFERENCES DEPARTAMENTO(DEP_ID)
)


INSERT INTO PAGO_TIPO(PAG_NOMBRE)VALUES
('TARJETA DE DEBITO'),
('TARJETA DE CREDITO'),
('DEPOSITO BANCARIO')

INSERT INTO CLIENTE (CLI_ID, CLI_NOMBRE, CLI_APELLIDOS, CLI_CELULAR, CLI_DIRECCION, CLI_FECHANA, CLI_TIPOPAGO) 
VALUES 
(1,'JUAN', 'PÉREZ GÓMEZ', '5551234567', 'AV. PRINCIPAL #123, CDMX', '1990-05-12', 1),
(2,'MARÍA', 'LOPEZ MARTÍNEZ', '5559876543', 'C. INDEPENDENCIA #45, GUADALAJARA', '1985-09-23', 2),
(3,'CARLOS', 'HERNÁNDEZ RAMÍREZ', '5563217890', 'AV. REFORMA #678, MONTERREY', '1992-11-30', 1),
(4,'ANA', 'GUTIÉRREZ FLORES', '5557412589', 'PASEO DE LA REFORMA #90, CDMX', '1988-07-15', 3),
(5,'PEDRO', 'MORALES SÁNCHEZ', '5589631470', 'COL. CENTRO #12, PUEBLA', '1995-03-27', 2);

ALTER PROCEDURE SP_MOSTRAR_CLIENTE
    @OP INT,  
    @CLI_ID INT = 0,  
    @CLI_NOMBRE VARCHAR(15) = '',  
    @CLI_APELLIDOS VARCHAR(100) = '',  
    @CLI_CELULAR VARCHAR(13) = '',  
    @CLI_DIRECCION VARCHAR(100) = '',  
    @CLI_FECHANA DATE = '',  
    @CLI_TIPOPAGO INT = 0  
AS
BEGIN
    -- CONSULTAR CLIENTES
    IF (@OP = 1)
    BEGIN
        SELECT CLI_ID, CLI_NOMBRE, CLI_APELLIDOS, CLI_CELULAR, CLI_DIRECCION, 
		CONVERT(VARCHAR(10), CLI_FECHANA, 103) AS CLI_FECHA, CLI_TIPOPAGO
		FROM CLIENTE;

    END

    -- AGREGAR/ACTUALIZAR CLIENTE
    ELSE IF (@OP = 2)
    BEGIN
        IF EXISTS (SELECT 1 FROM CLIENTE WHERE CLI_ID = @CLI_ID)
        BEGIN
            UPDATE CLIENTE 
            SET CLI_NOMBRE = @CLI_NOMBRE, 
                CLI_APELLIDOS = @CLI_APELLIDOS, 
                CLI_CELULAR = @CLI_CELULAR, 
                CLI_DIRECCION = @CLI_DIRECCION, 
                CLI_FECHANA = @CLI_FECHANA, 
                CLI_TIPOPAGO = @CLI_TIPOPAGO 
            WHERE CLI_ID = @CLI_ID;
        END
        ELSE
        BEGIN
            INSERT INTO CLIENTE (CLI_ID, CLI_NOMBRE, CLI_APELLIDOS, CLI_CELULAR, CLI_DIRECCION, CLI_FECHANA, CLI_TIPOPAGO) 
            VALUES ((SELECT ISNULL(MAX(CLI_ID),0) + 1 FROM CLIENTE), @CLI_NOMBRE, @CLI_APELLIDOS, @CLI_CELULAR, @CLI_DIRECCION, @CLI_FECHANA, @CLI_TIPOPAGO);
        END
    END

    -- BORRAR CLIENTE
    ELSE IF (@OP = 3)
    BEGIN
        DELETE FROM CLIENTE WHERE CLI_ID = @CLI_ID;
    END
END;

