CREATE DATABASE DBCARRITO
GO
USE DBCARRITO
GO
CREATE TABLE CATEGORIA
(
	CAT_ID INT PRIMARY KEY IDENTITY(1,1),
	CAT_DESCRIPCION VARCHAR(100) NOT NULL,
	CAT_ACTIVO BIT DEFAULT 1,
	CAT_FECHAREGISTRO DATETIME DEFAULT GETDATE()
)
GO
CREATE TABLE MARCA
(
	MAR_ID INT PRIMARY KEY IDENTITY(1,1),
	MAR_DESCRIPCION VARCHAR(100) NOT NULL,
	MAR_ACTIVO BIT DEFAULT 1,
	MAR_FECHAREGISTRO DATETIME DEFAULT GETDATE()
)
GO
CREATE TABLE PRODUCTO
(
	PROD_ID INT PRIMARY KEY IDENTITY(1,1),
	PROD_NOMBRE VARCHAR(500) NOT NULL,
	PROD_DESCRIPCION VARCHAR(500) NOT NULL,
	PROD_MAR_ID INT FOREIGN KEY REFERENCES MARCA(MAR_ID),
	PROD_CAT_ID INT FOREIGN KEY REFERENCES CATEGORIA(CAT_ID),
	PROD_PRECIO DECIMAL(10,2) DEFAULT 0 NOT NULL,
	PROD_STOCK INT NOT NULL,
	PROD_RUTAIMAGEN VARCHAR(100),
	PROD_NOMBREIMAGEN VARCHAR(100),
	PROD_ACTIVO BIT DEFAULT 1 NOT NULL,
	PROD_FECHAREGISTRO DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE CLIENTE
(
	CLI_ID INT PRIMARY KEY IDENTITY(1,1),
	CLI_NOMBRES VARCHAR(100) NOT NULL,
	CLI_APELLIDOS VARCHAR(100) NOT NULL,
	CLI_CORREO VARCHAR(100) NOT NULL,
	CLI_CLAVE VARCHAR(150) NOT NULL,
	CLI_RESTABLECER BIT DEFAULT 0,
	CLI_FECHAREGISTRO DATETIME DEFAULT GETDATE()
)
GO
CREATE TABLE CARRITO
(
	CARR_ID INT PRIMARY KEY IDENTITY(1,1),
	CARR_CLI_ID INT FOREIGN KEY REFERENCES CLIENTE(CLI_ID)NOT NULL,
	CARR_PROD_ID INT FOREIGN KEY REFERENCES PRODUCTO(PROD_ID)NOT NULL,
	CARR_CANTIAD INT NOT NULL
)
GO
CREATE TABLE VENTA
(
	VEN_ID INT PRIMARY KEY IDENTITY(1,1),
	VEN_CLI_ID INT FOREIGN KEY REFERENCES CLIENTE(CLI_ID)NOT NULL,
	VEN_TOTALPRODUCTO INT NOT NULL,
	VEN_MONTOTOTAL DECIMAL(10,2) NOT NULL,
	VEN_CONTACTO VARCHAR(50) NOT NULL,
	VEN_DIS_ID VARCHAR(10),
	VEN_TELEFONO VARCHAR(50) NOT NULL,
	VEN_DIRECCION VARCHAR(500),
	VEN_TRANS_ID VARCHAR(50),
	VEN_FECHAVENTA DATETIME DEFAULT GETDATE()
)
GO
CREATE TABLE DETALLE_VENTA
(
	DETV_ID INT PRIMARY KEY IDENTITY(1,1),
	DETV_VEN_ID INT FOREIGN KEY REFERENCES VENTA(VEN_ID) NOT NULL,
	DETV_PROD_ID INT FOREIGN KEY REFERENCES PRODUCTO(PROD_ID)NOT NULL,
	DETV_CANTIDAD INT NOT NULL,
	DETV_TOTAL DECIMAL(10,2)NOT NULL
)
GO
CREATE TABLE USUARIO
(
	USU_ID INT PRIMARY KEY IDENTITY(1,1),
	USU_NOMBRES VARCHAR(100) NOT NULL,
	USU_APELLIDOS VARCHAR(100) NOT NULL,
	USU_CORREO VARCHAR(100) NOT NULL,
	USU_CLAVE VARCHAR(150) NOT NULL,
	USU_RESTABLECER BIT DEFAULT 1,
	USU_ACTIVO BIT DEFAULT 1,
	USU_FECHAREGISTRO DATETIME DEFAULT GETDATE()
)
GO
CREATE TABLE DEPARTAMENTO
(
	DEP_ID INT NOT NULL,
	DEP_DESCRIPCION VARCHAR(50) NOT NULL
)
GO 
CREATE TABLE PROVINCIA
(
	PROVI_ID INT NOT NULL,
	PROVI_DESCRIPCION VARCHAR(50) NOT NULL,
	PROVI_DEP_ID INT NOT NULL
)
GO
CREATE TABLE DISTRITO
(
	DIS_ID INT NOT NULL,
	DIS_DESCRIPCION VARCHAR(50)NOT NULL,
	DIS_PROV_ID INT NOT NULL,
	DIS_DEP_ID INT NOT NULL
)

SELECT * FROM DISTRITO WHERE DIS_PROV_ID = 4 AND DIS_DEP_ID = 1

--------------------------INSERTS----------------------------------------------------------------------------------------


-- DEPARTAMENTO: Sinaloa

INSERT INTO DEPARTAMENTO (DEP_ID, DEP_DESCRIPCION) VALUES (1, 'Sinaloa');


-- PROVINCIAS DE SINALOA

INSERT INTO PROVINCIA (PROVI_ID, PROVI_DESCRIPCION, PROVI_DEP_ID) VALUES (1, 'Culiacán', 1);
INSERT INTO PROVINCIA (PROVI_ID, PROVI_DESCRIPCION, PROVI_DEP_ID) VALUES (2, 'Mazatlán', 1);
INSERT INTO PROVINCIA (PROVI_ID, PROVI_DESCRIPCION, PROVI_DEP_ID) VALUES (3, 'Los Mochis', 1);
INSERT INTO PROVINCIA (PROVI_ID, PROVI_DESCRIPCION, PROVI_DEP_ID) VALUES (4, 'Guasave', 1);

-- DISTRITOS DE SINALOA

-- Culiacán
INSERT INTO DISTRITO (DIS_ID, DIS_DESCRIPCION, DIS_PROV_ID, DIS_DEP_ID) VALUES (1, 'Las Quintas', 1, 1);
INSERT INTO DISTRITO (DIS_ID, DIS_DESCRIPCION, DIS_PROV_ID, DIS_DEP_ID) VALUES (2, 'Alturas del Sur', 1, 1);

-- Mazatlán
INSERT INTO DISTRITO (DIS_ID, DIS_DESCRIPCION, DIS_PROV_ID, DIS_DEP_ID) VALUES (3, 'Centro', 2, 1);
INSERT INTO DISTRITO (DIS_ID, DIS_DESCRIPCION, DIS_PROV_ID, DIS_DEP_ID) VALUES (4, 'El Toreo', 2, 1);

-- Los Mochis
INSERT INTO DISTRITO (DIS_ID, DIS_DESCRIPCION, DIS_PROV_ID, DIS_DEP_ID) VALUES (5, 'Scally', 3, 1);
INSERT INTO DISTRITO (DIS_ID, DIS_DESCRIPCION, DIS_PROV_ID, DIS_DEP_ID) VALUES (6, 'Centro', 3, 1);

-- Guasave
INSERT INTO DISTRITO (DIS_ID, DIS_DESCRIPCION, DIS_PROV_ID, DIS_DEP_ID) VALUES (7, 'Bamoa', 4, 1);
INSERT INTO DISTRITO (DIS_ID, DIS_DESCRIPCION, DIS_PROV_ID, DIS_DEP_ID) VALUES (8, 'Cruz Blanca', 4, 1);


--------------------------INSERTS----------------------------------------------------------------------------------------

--------------------------USUARIO----------------------------------------------------------------------------------------
CREATE PROCEDURE SP_REGISTRARUSUARIO
(
    @NOMBRES VARCHAR(100),
    @APELLIDOS VARCHAR(100),
    @CORREO VARCHAR(100),
    @CLAVE VARCHAR(150),
    @ACTIVO BIT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO INT OUTPUT
)
AS
BEGIN
    SET @RESULTADO = 0;
    
    -- VERIFICAR SI EL CORREO YA EXISTE
    IF EXISTS (SELECT 1 FROM USUARIO WHERE USU_CORREO = @CORREO)
    BEGIN
        SET @MENSAJE = 'EL CORREO DEL USUARIO YA EXISTE';
    END
    ELSE
    BEGIN
        -- INSERTAR NUEVO USUARIO
        INSERT INTO USUARIO (USU_NOMBRES, USU_APELLIDOS, USU_CORREO, USU_CLAVE, USU_ACTIVO, USU_FECHAREGISTRO)
        VALUES (@NOMBRES, @APELLIDOS, @CORREO, @CLAVE, @ACTIVO, GETDATE());

        -- OBTENER EL ID DEL USUARIO INSERTADO
        SET @RESULTADO = SCOPE_IDENTITY();
        SET @MENSAJE = 'USUARIO REGISTRADO EXITOSAMENTE';
    END
END;
GO
ALTER PROCEDURE SP_EDITARUSUARIO
(
    @USU_ID INT,
    @NOMBRES VARCHAR(100),
    @APELLIDOS VARCHAR(100),
    @CORREO VARCHAR(100),
    @ACTIVO BIT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO BIT OUTPUT
)
AS
BEGIN
    SET @RESULTADO = 0;
    
    -- VERIFICAR SI EL CORREO YA EXISTE EN OTRO USUARIO
    IF EXISTS (SELECT 1 FROM USUARIO WHERE USU_CORREO = @CORREO AND USU_ID != @USU_ID)
    BEGIN
        SET @MENSAJE = 'EL CORREO DEL USUARIO YA EXISTE';
    END
    ELSE
    BEGIN
        -- ACTUALIZAR USUARIO
        UPDATE USUARIO
        SET 
            USU_NOMBRES = @NOMBRES,
            USU_APELLIDOS = @APELLIDOS,
            USU_CORREO = @CORREO,
            USU_ACTIVO = @ACTIVO
        WHERE USU_ID = @USU_ID;

        -- CONFIRMAR QUE SE ACTUALIZÓ CORRECTAMENTE
        SET @RESULTADO = 1;
        SET @MENSAJE = 'USUARIO ACTUALIZADO EXITOSAMENTE';
    END
END;

GO
--------------------------USUARIO----------------------------------------------------------------------------------------

--------------------------CATEGORIA----------------------------------------------------------------------------------------
CREATE PROCEDURE SP_REGISTRAR_CATEGORIA
(
    @DESCRIPCION VARCHAR(100),
    @ACTIVO BIT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO INT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    
    SET @RESULTADO = 0;
    
    -- VERIFICA SI LA CATEGORÍA YA EXISTE
    IF NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE CAT_DESCRIPCION = @DESCRIPCION)
    BEGIN
		SET @RESULTADO = 0
        -- INSERTA LA NUEVA CATEGORÍA
        INSERT INTO CATEGORIA (CAT_DESCRIPCION, CAT_ACTIVO)
        VALUES (@DESCRIPCION, @ACTIVO);

        -- OBTIENE EL ID INSERTADO
        SET @RESULTADO = SCOPE_IDENTITY();
        SET @MENSAJE = 'CATEGORÍA REGISTRADA EXITOSAMENTE.';
    END
    ELSE
		BEGIN
			-- MENSAJE DE ERROR SI YA EXISTE
			SET @MENSAJE = 'LA CATEGORÍA YA EXISTE.';
		END
END;
GO

ALTER PROCEDURE SP_EDITAR_CATEGORIA
(
    @CAT_ID INT,
    @CAT_DESCRIPCION VARCHAR(100),
    @CAT_ACTIVO BIT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO BIT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    
    SET @RESULTADO = 0;
    
    -- VERIFICAR SI EXISTE OTRA CATEGORÍA CON EL MISMO NOMBRE (EXCLUYENDO LA ACTUAL)
    IF NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE CAT_DESCRIPCION = @CAT_DESCRIPCION AND CAT_ID <> @CAT_ID)
    BEGIN
        -- ACTUALIZAR LA CATEGORÍA
        UPDATE CATEGORIA 
        SET CAT_DESCRIPCION = @CAT_DESCRIPCION, 
            CAT_ACTIVO = @CAT_ACTIVO
        WHERE CAT_ID = @CAT_ID;
        
        SET @RESULTADO = 1;
    END
    ELSE
    BEGIN
        -- MENSAJE SI LA CATEGORÍA YA EXISTE
        SET @MENSAJE = 'LA CATEGORÍA YA EXISTE.';
    END
END;

GO
ALTER PROCEDURE SP_ELIMINAR_CATEGORIA
(
    @CAT_ID INT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO BIT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    
    SET @RESULTADO = 0;
    
    -- VERIFICAR SI EXISTEN PRODUCTOS RELACIONADOS CON LA CATEGORÍA
    IF NOT EXISTS (SELECT 1 FROM PRODUCTO P WHERE P.PROD_CAT_ID = @CAT_ID)
    BEGIN
        -- ELIMINAR LA CATEGORÍA SI NO ESTÁ RELACIONADA
        DELETE FROM CATEGORIA WHERE CAT_ID = @CAT_ID;
        SET @RESULTADO = 1;
    END
    ELSE
    BEGIN
        -- MENSAJE SI LA CATEGORÍA TIENE PRODUCTOS RELACIONADOS
        SET @MENSAJE = 'LA CATEGORÍA SE ENCUENTRA RELACIONADA A UN PRODUCTO.';
    END
END;

GO

--------------------------CATEGORIA----------------------------------------------------------------------------------------
--------------------------MARCA----------------------------------------------------------------------------------------

CREATE PROCEDURE SP_REGISTRAR_MARCA
(
    @MAR_DESCRIPCION VARCHAR(100),
    @MAR_ACTIVO BIT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO INT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    
    SET @RESULTADO = 0;
    
    -- VERIFICAR SI LA MARCA YA EXISTE
    IF NOT EXISTS (SELECT 1 FROM MARCA WHERE MAR_DESCRIPCION = @MAR_DESCRIPCION)
		BEGIN
			-- INSERTAR NUEVA MARCA
			INSERT INTO MARCA (MAR_DESCRIPCION, MAR_ACTIVO)
			VALUES (@MAR_DESCRIPCION, @MAR_ACTIVO);

			-- OBTENER ID INSERTADO
			SET @RESULTADO = SCOPE_IDENTITY();
			SET @MENSAJE = 'MARCA REGISTRADA EXITOSAMENTE.';
		END
    ELSE
    BEGIN
        -- MENSAJE SI LA MARCA YA EXISTE
        SET @MENSAJE = 'LA MARCA YA EXISTE.';
    END
END;

GO

CREATE PROCEDURE SP_EDITAR_MARCA
(
    @MAR_ID INT,
    @MAR_DESCRIPCION VARCHAR(100),
    @MAR_ACTIVO BIT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO BIT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    
    SET @RESULTADO = 0;
    
    -- VERIFICAR SI YA EXISTE OTRA MARCA CON EL MISMO NOMBRE (EXCLUYENDO LA ACTUAL)
    IF NOT EXISTS (SELECT 1 FROM MARCA WHERE MAR_DESCRIPCION = @MAR_DESCRIPCION AND MAR_ID <> @MAR_ID)
    BEGIN
        -- ACTUALIZAR LA MARCA
        UPDATE MARCA 
        SET MAR_DESCRIPCION = @MAR_DESCRIPCION, 
            MAR_ACTIVO = @MAR_ACTIVO
        WHERE MAR_ID = @MAR_ID;
        
        SET @RESULTADO = 1;
    END
    ELSE
    BEGIN
        -- MENSAJE SI LA MARCA YA EXISTE
        SET @MENSAJE = 'LA MARCA YA EXISTE.';
    END
END;

GO

CREATE PROCEDURE SP_ELIMINAR_MARCA
(
    @MAR_ID INT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO BIT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    
    SET @RESULTADO = 0;
    
    -- VERIFICAR SI LA MARCA ESTÁ RELACIONADA CON ALGÚN PRODUCTO
    IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE PROD_MAR_ID = @MAR_ID)
    BEGIN
        -- ELIMINAR LA MARCA SI NO ESTÁ RELACIONADA
        DELETE FROM MARCA WHERE MAR_ID = @MAR_ID;
        SET @RESULTADO = 1;
    END
    ELSE
    BEGIN
        -- MENSAJE SI LA MARCA TIENE PRODUCTOS ASOCIADOS
        SET @MENSAJE = 'LA MARCA SE ENCUENTRA RELACIONADA A UN PRODUCTO.';
    END
END;

GO 

--------------------------MARCA----------------------------------------------------------------------------------------

--------------------------PRODUCTO----------------------------------------------------------------------------------------

CREATE PROCEDURE SP_REGISTRAR_PRODUCTO 
(
    @PROD_NOMBRE VARCHAR(500),
    @PROD_DESCRIPCION VARCHAR(500),
    @PROD_MAR_ID INT,
    @PROD_CAT_ID INT,
    @PROD_PRECIO DECIMAL(10,2),
    @PROD_STOCK INT,
    @PROD_ACTIVO BIT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO INT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    
    SET @RESULTADO = 0;
    
    -- VERIFICAR SI EL PRODUCTO YA EXISTE CON EL MISMO NOMBRE
    IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE PROD_NOMBRE = @PROD_NOMBRE)
    BEGIN
        -- INSERTAR EL PRODUCTO
        INSERT INTO PRODUCTO (PROD_NOMBRE, PROD_DESCRIPCION, PROD_MAR_ID, PROD_CAT_ID, PROD_PRECIO, PROD_STOCK, PROD_ACTIVO)
        VALUES (@PROD_NOMBRE, @PROD_DESCRIPCION, @PROD_MAR_ID, @PROD_CAT_ID, @PROD_PRECIO, @PROD_STOCK, @PROD_ACTIVO);

        -- OBTENER ID INSERTADO
        SET @RESULTADO = SCOPE_IDENTITY();
        SET @MENSAJE = 'PRODUCTO REGISTRADO EXITOSAMENTE.';
    END
    ELSE
    BEGIN
        -- MENSAJE SI EL PRODUCTO YA EXISTE
        SET @MENSAJE = 'EL PRODUCTO YA EXISTE.';
    END
END;

GO

CREATE PROCEDURE SP_EDITAR_PRODUCTO (
    @PROD_ID INT,
    @PROD_NOMBRE VARCHAR(500),
    @PROD_DESCRIPCION VARCHAR(500),
    @PROD_MAR_ID INT,
    @PROD_CAT_ID INT,
    @PROD_PRECIO DECIMAL(10,2),
    @PROD_STOCK INT,
    @PROD_ACTIVO BIT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO BIT OUTPUT
) 
AS 
BEGIN 
    SET NOCOUNT ON; 
    SET @RESULTADO = 0; 
    
    -- VERIFICAR SI EXISTE OTRO PRODUCTO CON EL MISMO NOMBRE (EXCLUYENDO EL ACTUAL)
    IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE PROD_NOMBRE = @PROD_NOMBRE AND PROD_ID <> @PROD_ID) 
    BEGIN 
        -- ACTUALIZAR EL PRODUCTO
        UPDATE PRODUCTO 
        SET PROD_NOMBRE = @PROD_NOMBRE, 
            PROD_DESCRIPCION = @PROD_DESCRIPCION, 
            PROD_MAR_ID = @PROD_MAR_ID, 
            PROD_CAT_ID = @PROD_CAT_ID, 
            PROD_PRECIO = @PROD_PRECIO, 
            PROD_STOCK = @PROD_STOCK, 
            PROD_ACTIVO = @PROD_ACTIVO
        WHERE PROD_ID = @PROD_ID;
        
        SET @RESULTADO = 1; 
        SET @MENSAJE = 'PRODUCTO ACTUALIZADO EXITOSAMENTE.'; 
    END 
    ELSE 
    BEGIN 
        SET @MENSAJE = 'YA EXISTE OTRO PRODUCTO CON ESE NOMBRE.'; 
    END 
END;

GO

ALTER PROCEDURE SP_ELIMINAR_PRODUCTO (
    @PROD_ID INT,
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO BIT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    SET @RESULTADO = 0;

    -- VERIFICAR SI EL PRODUCTO ESTA INCLUIDO EN UNA VENTA
    IF NOT EXISTS (SELECT 1 FROM DETALLE_VENTA DV 
	INNER JOIN PRODUCTO P ON P.PROD_ID = DV.DETV_PROD_ID
	WHERE P.PROD_ID = @PROD_ID)
    BEGIN
        DELETE TOP(1) FROM PRODUCTO WHERE PROD_ID = @PROD_ID;
        SET @RESULTADO = 1;
        SET @MENSAJE = 'PRODUCTO ELIMINADO EXITOSAMENTE.';
    END
    ELSE
    BEGIN
        SET @MENSAJE = 'EL PRODUCTO SE ENCUENTRA RELACIONADO A UNA VENTA.';
    END
END;

SELECT P.PROD_ID,P.PROD_NOMBRE,P.PROD_DESCRIPCION,M.MAR_ID,
M.MAR_DESCRIPCION[DES_MARCA], C.CAT_ID,C.CAT_DESCRIPCION[CAT_DESCRIPCION],
P.PROD_PRECIO, P.PROD_STOCK, P.PROD_RUTAIMAGEN,P.PROD_NOMBREIMAGEN,
P.PROD_ACTIVO FROM PRODUCTO P
INNER JOIN MARCA M  ON M.MAR_ID = P.PROD_MAR_ID
INNER JOIN CATEGORIA C ON C.CAT_ID = P.PROD_CAT_ID
--------------------------PRODUCTO----------------------------------------------------------------------------------------
--------------------------DASHBOARD----------------------------------------------------------------------------------------

CREATE PROCEDURE SP_REPORTEDASHBOARD
AS
BEGIN
	SELECT
		(SELECT COUNT(*) FROM CLIENTE) [TotalCliente],
		(SELECT ISNULL(SUM(DETV_CANTIDAD),0) FROM DETALLE_VENTA) [TotalVenta],
		(SELECT COUNT(*) FROM PRODUCTO) [TotalProducto]
END

exec SP_REPORTEDASHBOARD

EXEC SP_REPORTEVENTAS 
    '02/06/2025', -- fecha inicio
    '02/06/2025', -- fecha fin
    '';           -- sin filtro por transacción



CREATE PROCEDURE SP_REPORTEVENTAS(
	@fechainicio varchar(10),
	@fechafin varchar(10),
	@idtransaccion varchar(50)

)
AS 
BEGIN

	SET DATEFORMAT DMY;

	SELECT CONVERT(CHAR(10),V.VEN_FECHAVENTA,103)[FechaVenta],CONCAT(C.CLI_NOMBRES,' ',C.CLI_APELLIDOS)[Cliente],
	P.PROD_NOMBRE[Producto],P.PROD_PRECIO[Precio],DV.DETV_CANTIDAD[Cantidad],DV.DETV_TOTAL[Total],V.VEN_TRANS_ID[IdTransaccion] 
	FROM DETALLE_VENTA DV
	INNER JOIN PRODUCTO P ON P.PROD_ID = DV.DETV_PROD_ID
	INNER JOIN VENTA V ON V.VEN_ID = DV.DETV_VEN_ID
	INNER JOIN CLIENTE C ON C.CLI_ID = V.VEN_CLI_ID
	WHERE CONVERT(DATE,V.VEN_FECHAVENTA) BETWEEN @fechainicio AND @fechafin

	AND V.VEN_TRANS_ID = IIF(@idtransaccion = '',V.VEN_TRANS_ID, @idtransaccion)
END

--------------------------DASHBOARD----------------------------------------------------------------------------------------

--------------------------CLIENTE----------------------------------------------------------------------------------------

CREATE PROCEDURE SP_REGISTRAR_CLIENTE
(
    @CLI_NOMBRES VARCHAR(100),
    @CLI_APELLIDOS VARCHAR(100),
    @CLI_CORREO VARCHAR(100),
    @CLI_CLAVE VARCHAR(150),
    @RESULTADO INT OUTPUT,
    @MENSAJE VARCHAR(500) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    SET @RESULTADO = 0;

    IF NOT EXISTS (SELECT 1 FROM CLIENTE WHERE CLI_CORREO = @CLI_CORREO)
    BEGIN
        INSERT INTO CLIENTE (CLI_NOMBRES, CLI_APELLIDOS, CLI_CORREO, CLI_CLAVE, CLI_RESTABLECER)
        VALUES (@CLI_NOMBRES, @CLI_APELLIDOS, @CLI_CORREO, @CLI_CLAVE, 0);

        SET @RESULTADO = SCOPE_IDENTITY();

        SET @MENSAJE = 'CLIENTE REGISTRADO CORRECTAMENTE';
    END
    ELSE
    BEGIN
        SET @MENSAJE = 'EL CORREO DEL CLIENTE YA EXISTE';
    END
END;
GO

DECLARE @IDCATEGORIA INT = 0

SELECT DISTINCT M.MAR_ID, M.MAR_DESCRIPCION FROM PRODUCTO P 
INNER JOIN CATEGORIA C ON C.CAT_ID = P.PROD_CAT_ID
INNER JOIN MARCA M ON M.MAR_ID = P.PROD_MAR_ID AND M.MAR_ACTIVO = 1
WHERE C.CAT_ID = IIF(@IDCATEGORIA = 0, C.CAT_ID, @IDCATEGORIA)

--------------------------CLIENTE----------------------------------------------------------------------------------------

--------------------------CARRITO----------------------------------------------------------------------------------------

CREATE PROCEDURE SP_EXISTECARRITO
(
    @CLI_ID INT,
    @PROD_ID INT,
    @RESULTADO BIT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    
    IF EXISTS(SELECT 1 
              FROM CARRITO 
              WHERE CARR_CLI_ID = @CLI_ID 
                AND CARR_PROD_ID = @PROD_ID)
    BEGIN
        SET @RESULTADO = 1;
    END
    ELSE
    BEGIN
        SET @RESULTADO = 0;
    END
END;
GO

CREATE PROCEDURE SP_OPERACIONCARRITO
(
    @IDCLIENTE   INT,
    @IDPRODUCTO  INT,
    @SUMAR       BIT,
    @MENSAJE     VARCHAR(500) OUTPUT,
    @RESULTADO   BIT OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    -- INICIALIZAMOS VALORES
    SET @MENSAJE   = '';
    SET @RESULTADO = 1;

    DECLARE @EXISTECARRITO BIT = IIF(EXISTS(SELECT * FROM CARRITO WHERE CARR_CLI_ID = @IDCLIENTE AND CARR_PROD_ID = @IDPRODUCTO),1,0)
	DECLARE @STOCKPRODUCTO INT = (SELECT PROD_STOCK FROM PRODUCTO WHERE PROD_ID = @IDPRODUCTO)

	BEGIN TRY
		BEGIN TRANSACTION OPERACION

		IF(@SUMAR = 1)
		BEGIN

			IF(@STOCKPRODUCTO > 0)
			BEGIN

				IF(@EXISTECARRITO = 1)
					UPDATE CARRITO SET CARR_CANTIAD = CARR_CANTIAD + 1 WHERE CARR_CLI_ID = @IDCLIENTE AND CARR_PROD_ID = @IDPRODUCTO
				ELSE
					INSERT INTO CARRITO(CARR_CLI_ID,CARR_PROD_ID,CARR_CANTIAD) VALUES(@IDCLIENTE,@IDPRODUCTO,1)

				UPDATE PRODUCTO SET PROD_STOCK = PROD_STOCK - 1 WHERE PROD_ID = @IDPRODUCTO

			END
			ELSE
			BEGIN
				SET @RESULTADO = 0
				SET @MENSAJE = 'EL PRODUCTO NO CUENTA CON STOCK DISPONIBLE'
			END

		END
		ELSE
		BEGIN
			UPDATE CARRITO SET CARR_CANTIAD = CARR_CANTIAD - 1 WHERE CARR_CLI_ID = @IDCLIENTE AND CARR_PROD_ID = @IDPRODUCTO
			UPDATE PRODUCTO SET PROD_STOCK = PROD_STOCK + 1 WHERE PROD_ID = @IDPRODUCTO
		END

		COMMIT TRANSACTION OPERACION
	END TRY
	BEGIN CATCH
		SET @RESULTADO = 0
		SET @MENSAJE = ERROR_MESSAGE()
		ROLLBACK TRANSACTION OPERACION
	END CATCH
END;
GO

SELECT COUNT(*) FROM CARRITO WHERE CARR_CLI_ID = 1

SELECT * FROM FN_OBTENERCARRITOCLIENTE(1)  -- Usa un ID válido


CREATE FUNCTION FN_OBTENERCARRITOCLIENTE(
	@idcliente int
)
RETURNS TABLE
AS
RETURN(
	SELECT P.PROD_ID,M.MAR_DESCRIPCION[DesMarca],P.PROD_NOMBRE,P.PROD_PRECIO,C.CARR_CANTIAD,P.PROD_RUTAIMAGEN,P.PROD_NOMBREIMAGEN
	FROM CARRITO C
	INNER JOIN PRODUCTO P ON P.PROD_ID = C.CARR_PROD_ID
	INNER JOIN MARCA M ON M.MAR_ID = P.PROD_MAR_ID
	WHERE C.CARR_CLI_ID = @idcliente
)

SELECT * FROM FN_OBTENERCARRITOCLIENTE(1)

CREATE PROC sp_EliminarCarrito
(
    @IdCliente INT,
    @IdProducto INT,
    @Resultado BIT OUTPUT
)
AS
BEGIN
    SET @Resultado = 1

    DECLARE @cantidadproducto INT = (
        SELECT CARR_CANTIAD 
        FROM CARRITO 
        WHERE CARR_CLI_ID = @IdCliente AND CARR_PROD_ID = @IdProducto
    )

    BEGIN TRY

        BEGIN TRANSACTION OPERACION

        UPDATE PRODUCTO 
        SET PROD_STOCK = PROD_STOCK + @cantidadproducto 
        WHERE PROD_ID = @IdProducto

        DELETE TOP (1) 
        FROM CARRITO 
        WHERE CARR_CLI_ID = @IdCliente AND CARR_PROD_ID = @IdProducto

        COMMIT TRANSACTION OPERACION

    END TRY
    BEGIN CATCH
        SET @Resultado = 0
        ROLLBACK TRANSACTION OPERACION
    END CATCH
END


--------------------------CARRITO----------------------------------------------------------------------------------------
--------------------------VENTA----------------------------------------------------------------------------------------

CREATE TYPE [dbo].[T_DETALLE_VENTA] AS TABLE
(
    [IdProducto] INT NULL,
    [Cantidad] INT NULL,
    [Total] DECIMAL(18, 2) NULL
);

CREATE PROCEDURE usp_RegistrarVenta
(
    @IdCliente INT,
    @TotalProducto INT,
    @MontoTotal DECIMAL(10, 2),
    @Contacto VARCHAR(50),
    @IdDistrito VARCHAR(10),
    @Telefono VARCHAR(50),
    @Direccion VARCHAR(500),
    @IdTransaccion VARCHAR(50),
    @DetalleVenta [T_DETALLE_VENTA] READONLY,
    @Resultado BIT OUTPUT,
    @Mensaje VARCHAR(500) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        DECLARE @IdVenta INT = 0
        SET @Resultado = 1
        SET @Mensaje = ''

        BEGIN TRANSACTION registro

        -- Insertar en tabla VENTA
        INSERT INTO VENTA
        (
            VEN_CLI_ID,
            VEN_TOTALPRODUCTO,
            VEN_MONTOTOTAL,
            VEN_CONTACTO,
            VEN_DIS_ID,
            VEN_TELEFONO,
            VEN_DIRECCION,
            VEN_TRANS_ID
        )
        VALUES
        (
            @IdCliente,
            @TotalProducto,
            @MontoTotal,
            @Contacto,
            @IdDistrito,
            @Telefono,
            @Direccion,
            @IdTransaccion
        )

        SET @IdVenta = SCOPE_IDENTITY()

        -- Insertar detalle de venta
        INSERT INTO DETALLE_VENTA
        (
            DETV_VEN_ID,
            DETV_PROD_ID,
            DETV_CANTIDAD,
            DETV_TOTAL
        )
        SELECT
            @IdVenta,
            IdProducto,
            Cantidad,
            Total
        FROM @DetalleVenta

        -- Eliminar productos del carrito del cliente
        DELETE FROM CARRITO WHERE CARR_CLI_ID = @IdCliente

        COMMIT TRAN registro
    END TRY
    BEGIN CATCH
        SET @Resultado = 0
        SET @Mensaje = ERROR_MESSAGE()
        ROLLBACK TRAN registro
    END CATCH
END

--------------------------VENTA----------------------------------------------------------------------------------------
--===========================COMENTARIOS==================================================================================
CREATE TABLE COMENTARIO (
    COM_ID INT IDENTITY(1,1) PRIMARY KEY,
    COM_PROD_ID INT NOT NULL FOREIGN KEY REFERENCES PRODUCTO(PROD_ID), 
    COM_CLI_ID INT NOT NULL FOREIGN KEY REFERENCES CLIENTE(CLI_ID),  
    COM_PUNTUACION INT NOT NULL,
    COM_CONTENIDO VARCHAR(500),
    COM_FECHAREGISTRO DATETIME DEFAULT GETDATE()
)

-- 1. Procedimiento para GUARDAR comentario
CREATE PROCEDURE sp_RegistrarComentario
(
    @IdProducto INT,
    @IdCliente INT,
    @Puntuacion INT,
    @Contenido VARCHAR(700),
    @Resultado BIT OUTPUT,
    @Mensaje VARCHAR(500) OUTPUT
)
AS
BEGIN
    SET @Resultado = 1
    SET @Mensaje = ''

    BEGIN TRY
        INSERT INTO COMENTARIO (COM_PROD_ID, COM_CLI_ID, COM_PUNTUACION, COM_CONTENIDO)
        VALUES (@IdProducto, @IdCliente, @Puntuacion, @Contenido)
    END TRY
    BEGIN CATCH
        SET @Resultado = 0
        SET @Mensaje = ERROR_MESSAGE()
    END CATCH
END
GO

-- 2. Procedimiento para LISTAR comentarios de un producto

CREATE PROCEDURE sp_ListarComentarios
(
    @IdProducto INT
)
AS
BEGIN
    SELECT c.COM_ID, c.COM_PUNTUACION, c.COM_CONTENIDO, c.COM_FECHAREGISTRO,
           cl.CLI_NOMBRES
    FROM COMENTARIO c
    INNER JOIN CLIENTE cl ON c.COM_CLI_ID = cl.CLI_ID
    WHERE c.COM_PROD_ID = @IdProducto
    ORDER BY c.COM_FECHAREGISTRO DESC
END
GO

CREATE PROCEDURE sp_VerificarCompra
(
    @IdCliente INT,
    @IdProducto INT,
    @Comprado BIT OUTPUT
)
AS
BEGIN
    SET @Comprado = 0
    
    IF EXISTS(
        SELECT 1 
        FROM DETALLE_VENTA dv
        INNER JOIN VENTA v ON v.VEN_ID = dv.DETV_VEN_ID
        WHERE v.VEN_CLI_ID = @IdCliente AND dv.DETV_PROD_ID = @IdProducto
    )
    BEGIN
        SET @Comprado = 1
    END
END
GO
--===========================COMENTARIOS==================================================================================

CREATE TABLE CUPON (
    IdCupon INT PRIMARY KEY IDENTITY(1,1),
    Codigo VARCHAR(50) UNIQUE NOT NULL,
    Valor DECIMAL(10,2) NOT NULL,
    Tipo VARCHAR(20) NOT NULL,
    Activo BIT DEFAULT 1,
    FechaVencimiento DATETIME,
    
    -- Aquí va la restricción
    CONSTRAINT CK_Cupon_Tipo CHECK (Tipo IN ('FIJO', 'PORCENTAJE'))
);
